// Seed script to load real trade data into the database
// Run with: npx tsx src/scripts/seed.ts

import "dotenv/config";
import { PrismaClient } from "../generated/prisma/client.js";
import { PrismaPg } from "@prisma/adapter-pg";

const COMM_RATE = 0.000068848354793;
function comm(price: number, qty: number) {
  return Math.round(price * qty * COMM_RATE * 100) / 100;
}

interface TradeInput {
  date: string;
  month: number;
  symbol: string;
  direction: "LONG" | "SHORT";
  tradeType: string;
  isSwingContinuation: boolean;
  buyLegs: { price: number; qty: number }[];
  sellLegs: { price: number; qty: number }[];
  totalPnL: number | null;
  riskReward: number | null;
  returnOnPosition: number | null;
  positionValue: number;
  entryReason: string;
  exitReason: string | null;
  conclusions: string | null;
  chartUrl: string | null;
  dailyHigh: number | null;
  dailyClose: number | null;
}

async function main() {
  const connectionString = process.env.DIRECT_URL || process.env.DATABASE_URL || "";
  const adapter = new PrismaPg({ connectionString });
  const prisma = new PrismaClient({ adapter });

  console.log("Clearing existing data...");
  await prisma.tradeError.deleteMany();
  await prisma.tradeLeg.deleteMany();
  await prisma.trade.deleteMany();
  await prisma.errorDefinition.deleteMany();
  await prisma.assetLeverage.deleteMany();
  await prisma.monthlyReview.deleteMany();
  await prisma.account.deleteMany();

  console.log("Creating account...");
  const account = await prisma.account.create({
    data: {
      userId: "asaf",
      calendarYear: 2026,
      startingBalance: 178600,
      accountOpenBalance: 178600,
      commissionPerShare: COMM_RATE,
      minimumCommission: 0,
    },
  });

  // === MONTHLY REVIEWS ===
  console.log("Creating monthly reviews...");
  await prisma.monthlyReview.createMany({
    data: [
      { accountId: account.id, month: 1, year: 2026, portfolioStartValue: 178600, portfolioEndValue: 180103, useFixedRiskUnit: false, includeOpenTrades: true },
      { accountId: account.id, month: 2, year: 2026, portfolioStartValue: 180103, portfolioEndValue: 179556, riskUnit: 1000, useFixedRiskUnit: true, includeOpenTrades: true },
      { accountId: account.id, month: 3, year: 2026, portfolioStartValue: 179556, portfolioEndValue: 188991, riskUnit: 1000, useFixedRiskUnit: true, includeOpenTrades: true },
    ],
  });

  // === ASSET LEVERAGES (for futures/commodities) ===
  console.log("Creating asset leverages...");
  await prisma.assetLeverage.createMany({
    data: [
      { accountId: account.id, symbol: "Oil", leverage: 100 },
      { accountId: account.id, symbol: "Oil FTMO", leverage: 100 },
      { accountId: account.id, symbol: "Gold", leverage: 1 },
      { accountId: account.id, symbol: "S&P", leverage: 10 },
      { accountId: account.id, symbol: "EUR-USD", leverage: 100000 },
      { accountId: account.id, symbol: "Bitcoin FTMO", leverage: 1 },
    ],
  });

  // === ALL TRADES ===
  const trades: TradeInput[] = [
    // ===== JANUARY =====
    {
      date: "2026-01-26", month: 1, symbol: "PG", direction: "LONG", tradeType: "Retest Long",
      isSwingContinuation: false,
      buyLegs: [{ price: 148.87, qty: 141 }],
      sellLegs: [{ price: 164.23, qty: 70 }, { price: 155.00, qty: 71 }],
      totalPnL: 1502.58, riskReward: null, returnOnPosition: 0.0716, positionValue: 20991,
      entryReason: "Retest scenario", exitReason: "Sold 50%, securing part of the return (up to 10.5%)",
      conclusions: "Trade is currently working according to plan",
      chartUrl: "https://www.tradingview.com/x/FDdojBmh/",
      dailyHigh: 150.88, dailyClose: 149.49,
    },

    // ===== FEBRUARY =====
    {
      date: "2026-02-03", month: 2, symbol: "BKE", direction: "LONG", tradeType: "Retest Long",
      isSwingContinuation: false,
      buyLegs: [{ price: 48.10, qty: 31 }],
      sellLegs: [{ price: 54.48, qty: 31 }],
      totalPnL: 192.78, riskReward: 0.19, returnOnPosition: 0.1293, positionValue: 1491,
      entryReason: "Touch on support line, Fib 0.618 line", exitReason: "Reached TP",
      conclusions: null, chartUrl: "https://www.tradingview.com/x/nG6z4jMU/",
      dailyHigh: 49.64, dailyClose: 48.99,
    },
    {
      date: "2026-02-04", month: 2, symbol: "NRG", direction: "LONG", tradeType: "Retest Long",
      isSwingContinuation: false,
      buyLegs: [{ price: 142.00, qty: 107 }],
      sellLegs: [{ price: 166.10, qty: 52 }, { price: 180.00, qty: 55 }],
      totalPnL: 3335.54, riskReward: 3.34, returnOnPosition: 0.2195, positionValue: 15194,
      entryReason: "Touch on support line", exitReason: "Reached TP",
      conclusions: null, chartUrl: "https://www.tradingview.com/x/FRbqGBWL/",
      dailyHigh: 153.47, dailyClose: 143.99,
    },
    {
      date: "2026-02-04", month: 2, symbol: "ONDS", direction: "LONG", tradeType: "Retest Long",
      isSwingContinuation: false,
      buyLegs: [{ price: 10.11, qty: 700 }],
      sellLegs: [{ price: 8.69, qty: 700 }],
      totalPnL: -1006.53, riskReward: -1.01, returnOnPosition: -0.1422, positionValue: 7077,
      entryReason: "Exit at SL", exitReason: null,
      conclusions: null, chartUrl: null,
      dailyHigh: 11.40, dailyClose: 9.68,
    },
    {
      date: "2026-02-02", month: 2, symbol: "SMR", direction: "LONG", tradeType: "Retest Long",
      isSwingContinuation: false,
      buyLegs: [{ price: 16.67, qty: 270 }],
      sellLegs: [{ price: 9.79, qty: 270 }],
      totalPnL: -1862.21, riskReward: -1.86, returnOnPosition: -0.4137, positionValue: 4501,
      entryReason: "Significant resistance line, M reversal pattern completion", exitReason: null,
      conclusions: null, chartUrl: "https://www.tradingview.com/x/eghJN0Nb/",
      dailyHigh: 17.42, dailyClose: 16.48,
    },
    {
      date: "2026-02-05", month: 2, symbol: "MDGL", direction: "LONG", tradeType: "Retest Long",
      isSwingContinuation: false,
      buyLegs: [{ price: 463.36, qty: 23 }],
      sellLegs: [{ price: 433.25, qty: 23 }],
      totalPnL: -697.53, riskReward: -0.70, returnOnPosition: -0.0655, positionValue: 10657,
      entryReason: "Support line, Fib 0.382 line", exitReason: "Exit at SL",
      conclusions: "Stock went down", chartUrl: "https://www.tradingview.com/x/e62qo3xl/",
      dailyHigh: 486.88, dailyClose: 463.42,
    },
    {
      date: "2026-02-06", month: 2, symbol: "AMZN", direction: "LONG", tradeType: "Retest Long",
      isSwingContinuation: false,
      buyLegs: [{ price: 202.63, qty: 7 }],
      sellLegs: [{ price: 197.36, qty: 7 }],
      totalPnL: -41.88, riskReward: -0.04, returnOnPosition: -0.0295, positionValue: 1418,
      entryReason: "Touch on resistance line, support and retest level", exitReason: "Exit at SL",
      conclusions: "Short SL", chartUrl: "https://www.tradingview.com/x/TrnmT6LE/",
      dailyHigh: 211.44, dailyClose: 210.32,
    },
    {
      date: "2026-02-09", month: 2, symbol: "ONDS", direction: "LONG", tradeType: "Retest Long",
      isSwingContinuation: false,
      buyLegs: [{ price: 9.80, qty: 67 }],
      sellLegs: [{ price: 11.25, qty: 67 }],
      totalPnL: 92.15, riskReward: 0.09, returnOnPosition: 0.1403, positionValue: 657,
      entryReason: "Early entry", exitReason: null,
      conclusions: null, chartUrl: "https://www.tradingview.com/x/APNdLrb9/",
      dailyHigh: 10.64, dailyClose: 10.34,
    },
    {
      date: "2026-02-10", month: 2, symbol: "QBTS", direction: "LONG", tradeType: "Retest Long",
      isSwingContinuation: false,
      buyLegs: [{ price: 20.76, qty: 246 }],
      sellLegs: [{ price: 16.55, qty: 246 }],
      totalPnL: -1040.66, riskReward: -1.04, returnOnPosition: -0.2038, positionValue: 5107,
      entryReason: "Breakout of resistance level, retest point", exitReason: "Stopped out at SL",
      conclusions: "Entry at wrong point, M reversal pattern - entered too early",
      chartUrl: "https://www.tradingview.com/x/tMHSSrmS/",
      dailyHigh: 21.52, dailyClose: 20.44,
    },
    {
      date: "2026-02-10", month: 2, symbol: "ARM", direction: "LONG", tradeType: "Breakout",
      isSwingContinuation: false,
      buyLegs: [{ price: 124.50, qty: 49 }],
      sellLegs: [{ price: 132.41, qty: 49 }],
      totalPnL: 382.59, riskReward: 0.38, returnOnPosition: 0.0627, positionValue: 6101,
      entryReason: "M reversal pattern completion, high volume, full candle", exitReason: null,
      conclusions: null, chartUrl: "https://www.tradingview.com/x/Nr0JqU4P/",
      dailyHigh: 130.90, dailyClose: 125.95,
    },
    {
      date: "2026-02-11", month: 2, symbol: "RKLB", direction: "LONG", tradeType: "Retest Long",
      isSwingContinuation: false,
      buyLegs: [{ price: 69.92, qty: 148.98 }],
      sellLegs: [{ price: 71.75, qty: 141 }],
      totalPnL: 252.51, riskReward: 0.25, returnOnPosition: 0.0242, positionValue: 10417,
      entryReason: "Retest point, Fib 0.5, weakening sell volumes", exitReason: "Sell before earning call",
      conclusions: "Good call", chartUrl: "https://www.tradingview.com/x/1cj1NwIp/",
      dailyHigh: 73.40, dailyClose: 69.62,
    },
    {
      date: "2026-02-12", month: 2, symbol: "ASTS", direction: "LONG", tradeType: "Retest Long",
      isSwingContinuation: true,
      buyLegs: [{ price: 88.00, qty: 90 }],
      sellLegs: [{ price: 105.79, qty: 45 }, { price: 77.981556, qty: 45 }],
      totalPnL: 342.22, riskReward: 0.34, returnOnPosition: 0.0432, positionValue: 7920,
      entryReason: "Retest point", exitReason: "Taking profits",
      conclusions: null, chartUrl: "https://www.tradingview.com/x/u7cQadNq/",
      dailyHigh: null, dailyClose: null,
    },
    {
      date: "2026-02-12", month: 2, symbol: "TME", direction: "LONG", tradeType: "Retest Long",
      isSwingContinuation: true,
      buyLegs: [{ price: 15.39, qty: 493 }],
      sellLegs: [{ price: 13.35, qty: 493 }],
      totalPnL: -1015.58, riskReward: -1.02, returnOnPosition: -0.1339, positionValue: 7587,
      entryReason: "Retest point", exitReason: "Exit at stop loss",
      conclusions: "Stop too short", chartUrl: "https://www.tradingview.com/x/I0rYnXVx/",
      dailyHigh: null, dailyClose: null,
    },
    {
      date: "2026-02-13", month: 2, symbol: "EBAY", direction: "LONG", tradeType: "Retest Long",
      isSwingContinuation: true,
      buyLegs: [{ price: 81.40, qty: 170 }],
      sellLegs: [{ price: 92.43, qty: 170 }],
      totalPnL: 1870.10, riskReward: 1.87, returnOnPosition: 0.1351, positionValue: 13838,
      entryReason: "Retest point, Fib 0.382 point", exitReason: "Position realized",
      conclusions: null, chartUrl: "https://www.tradingview.com/x/p4WFsh3B/",
      dailyHigh: null, dailyClose: null,
    },
    {
      date: "2026-02-13", month: 2, symbol: "BAC", direction: "LONG", tradeType: "Retest Long",
      isSwingContinuation: true,
      buyLegs: [{ price: 51.56, qty: 353 }],
      sellLegs: [{ price: 48.73, qty: 353 }],
      totalPnL: -1006.05, riskReward: -1.01, returnOnPosition: -0.0553, positionValue: 18201,
      entryReason: "Retest point", exitReason: null,
      conclusions: null, chartUrl: "https://www.tradingview.com/x/8pfrth9L/",
      dailyHigh: null, dailyClose: null,
    },
    {
      date: "2026-02-18", month: 2, symbol: "PLTR", direction: "LONG", tradeType: "Retest Long",
      isSwingContinuation: false,
      buyLegs: [{ price: 135.00, qty: 40 }],
      sellLegs: [{ price: 150.33, qty: 40 }],
      totalPnL: 608.00, riskReward: 0.61, returnOnPosition: 0.1126, positionValue: 5400,
      entryReason: "Hammer candle - trend change, M reversal pattern completion", exitReason: null,
      conclusions: null, chartUrl: "https://www.tradingview.com/x/MD7mAhgy/",
      dailyHigh: 140.96, dailyClose: 135.38,
    },
    {
      date: "2026-02-18", month: 2, symbol: "EXE", direction: "LONG", tradeType: "Retest Long",
      isSwingContinuation: false,
      buyLegs: [{ price: 98.46, qty: 108 }],
      sellLegs: [{ price: 108.29, qty: 108 }],
      totalPnL: 1056.79, riskReward: 1.06, returnOnPosition: 0.0994, positionValue: 10634,
      entryReason: "Retest point", exitReason: null,
      conclusions: null, chartUrl: "https://www.tradingview.com/x/ssO9JE07/",
      dailyHigh: 104.93, dailyClose: 99.52,
    },
    {
      date: "2026-02-18", month: 2, symbol: "APP", direction: "LONG", tradeType: "Retest Long",
      isSwingContinuation: false,
      buyLegs: [{ price: 402.25, qty: 14 }],
      sellLegs: [],
      totalPnL: null, riskReward: null, returnOnPosition: null, positionValue: 5632,
      entryReason: "M reversal pattern, D9 green indicator", exitReason: null,
      conclusions: null, chartUrl: "https://www.tradingview.com/x/eN36Lbrp/",
      dailyHigh: 407.18, dailyClose: 404.39,
    },
    {
      date: "2026-02-18", month: 2, symbol: "SPOT", direction: "LONG", tradeType: "Retest Long",
      isSwingContinuation: true,
      buyLegs: [{ price: 479.00, qty: 17 }],
      sellLegs: [{ price: 551.80, qty: 9 }],
      totalPnL: 650.19, riskReward: 0.65, returnOnPosition: 0.0798, positionValue: 8143,
      entryReason: "Retest, Fib support, high volume, D9 green, CCI -200, RSI 30",
      exitReason: "Realized half position, sold 9 units",
      conclusions: null, chartUrl: "https://www.tradingview.com/x/7mh9D877/",
      dailyHigh: null, dailyClose: null,
    },
    {
      date: "2026-02-18", month: 2, symbol: "AVAV", direction: "LONG", tradeType: "Retest Long",
      isSwingContinuation: true,
      buyLegs: [{ price: 265.00, qty: 2.12 }],
      sellLegs: [{ price: 219.02, qty: 2.12 }],
      totalPnL: -102.48, riskReward: -0.10, returnOnPosition: -0.1824, positionValue: 562,
      entryReason: "Touch on Fib lines, retest", exitReason: "Exit due to stop point reached",
      conclusions: null, chartUrl: "https://www.tradingview.com/x/oNzA89qf/",
      dailyHigh: null, dailyClose: null,
    },
    {
      date: "2026-02-18", month: 2, symbol: "IBM", direction: "LONG", tradeType: "Retest Long",
      isSwingContinuation: false,
      buyLegs: [{ price: 260.65, qty: 4.51 }],
      sellLegs: [{ price: 238.77, qty: 4.51 }],
      totalPnL: -103.68, riskReward: -0.10, returnOnPosition: -0.0882, positionValue: 1176,
      entryReason: "Cup and handle pattern, support point, buying volume",
      exitReason: "Exit due to stop points reached",
      conclusions: null, chartUrl: "https://www.tradingview.com/x/saodESlM/",
      dailyHigh: 261.11, dailyClose: 260.79,
    },
    {
      date: "2026-02-20", month: 2, symbol: "LMND", direction: "LONG", tradeType: "Retest Long",
      isSwingContinuation: false,
      buyLegs: [{ price: 59.50, qty: 80 }],
      sellLegs: [{ price: 64.15, qty: 80 }],
      totalPnL: 366.60, riskReward: 0.37, returnOnPosition: 0.0770, positionValue: 4760,
      entryReason: "Touch on Fib lines", exitReason: null,
      conclusions: null, chartUrl: "https://www.tradingview.com/x/eIhCCdcd/",
      dailyHigh: 60.69, dailyClose: 57.31,
    },
    {
      date: "2026-02-20", month: 2, symbol: "EXPE", direction: "LONG", tradeType: "Retest Long",
      isSwingContinuation: false,
      buyLegs: [{ price: 202.28, qty: 32.7761 }],
      sellLegs: [{ price: 251.04, qty: 32.7761 }],
      totalPnL: 1593.29, riskReward: 1.59, returnOnPosition: 0.2403, positionValue: 6630,
      entryReason: "Retest, Fib support", exitReason: "Position realized",
      conclusions: null, chartUrl: "https://www.tradingview.com/x/kiryil9l/",
      dailyHigh: 206.53, dailyClose: 203.48,
    },
    {
      date: "2026-02-20", month: 2, symbol: "HUGB", direction: "LONG", tradeType: "Retest Long",
      isSwingContinuation: false,
      buyLegs: [{ price: 42.30, qty: 20.87 }],
      sellLegs: [{ price: 37.48, qty: 20.87 }],
      totalPnL: -105.59, riskReward: -0.11, returnOnPosition: -0.1196, positionValue: 883,
      entryReason: "3 bearish candles, support on daily chart", exitReason: null,
      conclusions: null, chartUrl: "https://www.tradingview.com/x/wfbriorK/",
      dailyHigh: null, dailyClose: null,
    },
    {
      date: "2026-02-23", month: 2, symbol: "COF", direction: "LONG", tradeType: "Retest Long",
      isSwingContinuation: true,
      buyLegs: [{ price: 201.07, qty: 60 }],
      sellLegs: [{ price: 185.49, qty: 60 }],
      totalPnL: -939.54, riskReward: -0.94, returnOnPosition: -0.0779, positionValue: 12064,
      entryReason: "Retest", exitReason: null,
      conclusions: null, chartUrl: "https://www.tradingview.com/x/KPfRyRpL/",
      dailyHigh: null, dailyClose: null,
    },
    {
      date: "2026-02-23", month: 2, symbol: "SAP", direction: "LONG", tradeType: "Retest Long",
      isSwingContinuation: false,
      buyLegs: [{ price: 199.17, qty: 58.3 }],
      sellLegs: [{ price: 175.94, qty: 58.309 }],
      totalPnL: -1359.04, riskReward: -1.36, returnOnPosition: -0.1170, positionValue: 11613,
      entryReason: "Retest, Bollinger bands support, RSI 30, CCI -210", exitReason: null,
      conclusions: null, chartUrl: "https://www.tradingview.com/x/V01RrJoq/",
      dailyHigh: 199.22, dailyClose: 196.71,
    },
    {
      date: "2026-02-23", month: 2, symbol: "ALAB", direction: "LONG", tradeType: "Retest Long",
      isSwingContinuation: false,
      buyLegs: [{ price: 127.23, qty: 31 }],
      sellLegs: [],
      totalPnL: null, riskReward: null, returnOnPosition: null, positionValue: 3944,
      entryReason: "Retest line, Fib lines, Bollinger band support, CCI -200", exitReason: null,
      conclusions: null, chartUrl: "https://www.tradingview.com/x/4mpXjMwj/",
      dailyHigh: 128.56, dailyClose: 128.24,
    },
    {
      date: "2026-02-23", month: 2, symbol: "MSFT", direction: "LONG", tradeType: "Retest Long",
      isSwingContinuation: false,
      buyLegs: [{ price: 395.00, qty: 17 }],
      sellLegs: [],
      totalPnL: null, riskReward: null, returnOnPosition: null, positionValue: 6715,
      entryReason: "Retest line, RSI and CCI touching", exitReason: null,
      conclusions: null, chartUrl: "https://www.tradingview.com/x/1m3vIxaJ/",
      dailyHigh: 395.36, dailyClose: 384.47,
    },
    {
      date: "2026-02-23", month: 2, symbol: "JPM", direction: "LONG", tradeType: "Retest Long",
      isSwingContinuation: false,
      buyLegs: [{ price: 295.19, qty: 60 }],
      sellLegs: [{ price: 280.74, qty: 60 }],
      totalPnL: -872.00, riskReward: -0.87, returnOnPosition: -0.0492, positionValue: 17711,
      entryReason: "Retest line, Bollinger band as support", exitReason: "Stopped out at SL",
      conclusions: null, chartUrl: "https://www.tradingview.com/x/zo5zWRDy/",
      dailyHigh: 311.00, dailyClose: 297.67,
    },
    {
      date: "2026-02-24", month: 2, symbol: "RYTM", direction: "LONG", tradeType: "Retest Long",
      isSwingContinuation: false,
      buyLegs: [{ price: 95.44, qty: 90 }],
      sellLegs: [{ price: 99.00, qty: 90 }],
      totalPnL: 315.40, riskReward: 0.32, returnOnPosition: 0.0367, positionValue: 8590,
      entryReason: "Fib 0.382, support line, Bollinger band support",
      exitReason: "Earning Call - next day",
      conclusions: null, chartUrl: "https://www.tradingview.com/x/UYgkRw2w/",
      dailyHigh: 99.69, dailyClose: 98.65,
    },
    {
      date: "2026-02-23", month: 2, symbol: "W", direction: "LONG", tradeType: "Retest Long",
      isSwingContinuation: false,
      buyLegs: [{ price: 75.10, qty: 6.49 }],
      sellLegs: [],
      totalPnL: null, riskReward: null, returnOnPosition: null, positionValue: 487,
      entryReason: "Support line, Bollinger band support, Fib 0.5", exitReason: null,
      conclusions: null, chartUrl: "https://www.tradingview.com/x/cFD2KLRi/",
      dailyHigh: 81.51, dailyClose: 73.47,
    },
    {
      date: "2026-02-25", month: 2, symbol: "BKNG", direction: "LONG", tradeType: "Retest Long",
      isSwingContinuation: true,
      buyLegs: [{ price: 4160.00, qty: 2.35 }],
      sellLegs: [{ price: 4600.00, qty: 1 }, { price: 4319.25, qty: 1.135 }],
      totalPnL: 613.25, riskReward: 0.61, returnOnPosition: 0.0627, positionValue: 9776,
      entryReason: "Support line, Fib 61.8%, CCI -200, RSI 30",
      exitReason: "Realized half position",
      conclusions: null, chartUrl: "https://www.tradingview.com/x/VgR7VSmF/",
      dailyHigh: 4179.50, dailyClose: 4163.00,
    },
    {
      date: "2026-02-25", month: 2, symbol: "AXP", direction: "LONG", tradeType: "Retest Long",
      isSwingContinuation: true,
      buyLegs: [{ price: 327.24, qty: 50.53 }],
      sellLegs: [{ price: 302.15, qty: 50.53 }],
      totalPnL: -1272.80, riskReward: -1.27, returnOnPosition: -0.0770, positionValue: 16535,
      entryReason: "Resistance becoming support, CCI -200, RSI 42", exitReason: null,
      conclusions: null, chartUrl: "https://www.tradingview.com/x/FQWhFzc0/",
      dailyHigh: 329.13, dailyClose: 327.09,
    },
    {
      date: "2026-02-27", month: 2, symbol: "FOXA", direction: "LONG", tradeType: "Retest Long",
      isSwingContinuation: false,
      buyLegs: [{ price: 55.97, qty: 110 }],
      sellLegs: [{ price: 57.82, qty: 110 }],
      totalPnL: 198.50, riskReward: 0.20, returnOnPosition: 0.0322, positionValue: 6157,
      entryReason: "Support line, Bollinger support, CCI reached -240", exitReason: null,
      conclusions: null, chartUrl: "https://www.tradingview.com/x/E4bdnTJQ/",
      dailyHigh: 56.93, dailyClose: 56.34,
    },
    {
      date: "2026-02-27", month: 2, symbol: "SOFI", direction: "LONG", tradeType: "Retest Long",
      isSwingContinuation: false,
      buyLegs: [{ price: 18.18, qty: 230 }],
      sellLegs: [],
      totalPnL: null, riskReward: null, returnOnPosition: null, positionValue: 4181,
      entryReason: "Support line, Fib 0.61, D9 green weekly, CCI -200, RSI 30", exitReason: null,
      conclusions: null, chartUrl: "https://www.tradingview.com/x/QuNRQoXJ/",
      dailyHigh: 18.21, dailyClose: 17.76,
    },
    {
      date: "2026-02-27", month: 2, symbol: "BABA", direction: "LONG", tradeType: "Retest Long",
      isSwingContinuation: true,
      buyLegs: [{ price: 145.93, qty: 60 }],
      sellLegs: [{ price: 129.50, qty: 60 }],
      totalPnL: -990.80, riskReward: -0.99, returnOnPosition: -0.1132, positionValue: 8756,
      entryReason: "Bollinger support, support line", exitReason: "Exit at SL",
      conclusions: null, chartUrl: "https://www.tradingview.com/x/FU9SmpFd/",
      dailyHigh: 146.40, dailyClose: 144.11,
    },

    // ===== MARCH =====
    { date: "2026-03-02", month: 3, symbol: "TSLA", direction: "LONG", tradeType: "Retest Long", isSwingContinuation: false,
      buyLegs: [{ price: 389.14, qty: 2.54 }], sellLegs: [],
      totalPnL: null, riskReward: null, returnOnPosition: null, positionValue: 988,
      entryReason: "Support line, Fib 0.382, Bollinger band support", exitReason: null,
      conclusions: null, chartUrl: "https://www.tradingview.com/x/gtO4YCaB/", dailyHigh: 404.54, dailyClose: 403.32 },
    { date: "2026-03-03", month: 3, symbol: "NFLX", direction: "LONG", tradeType: "Retest Long", isSwingContinuation: false,
      buyLegs: [{ price: 95.91, qty: 44 }], sellLegs: [],
      totalPnL: null, riskReward: null, returnOnPosition: null, positionValue: 4220,
      entryReason: "Fib 0.5", exitReason: null,
      conclusions: null, chartUrl: "https://www.tradingview.com/x/oOTbaHyQ/", dailyHigh: 98.46, dailyClose: 97.70 },
    { date: "2026-03-03", month: 3, symbol: "CG", direction: "LONG", tradeType: "Retest Long", isSwingContinuation: false,
      buyLegs: [{ price: 50.27, qty: 160 }], sellLegs: [],
      totalPnL: null, riskReward: null, returnOnPosition: null, positionValue: 8043,
      entryReason: "Head and shoulders reversal, support line, Fib 0.618", exitReason: null,
      conclusions: null, chartUrl: "https://www.tradingview.com/x/uTChyWdn/", dailyHigh: 52.11, dailyClose: 51.66 },
    { date: "2026-03-05", month: 3, symbol: "LLY", direction: "LONG", tradeType: "Retest Long", isSwingContinuation: false,
      buyLegs: [{ price: 966.60, qty: 15 }], sellLegs: [{ price: 899.73, qty: 15 }],
      totalPnL: -1008.01, riskReward: -1.01, returnOnPosition: -0.0695, positionValue: 14499,
      entryReason: "Support line", exitReason: null,
      conclusions: null, chartUrl: "https://www.tradingview.com/x/E1ZNnVMU/", dailyHigh: 993.56, dailyClose: 983.26 },
    { date: "2026-03-06", month: 3, symbol: "CL", direction: "LONG", tradeType: "Earnings", isSwingContinuation: false,
      buyLegs: [{ price: 86.00, qty: 1000 }, { price: 90.00, qty: 1000 }, { price: 91.00, qty: 1000 }],
      sellLegs: [{ price: 90.00, qty: 1000 }, { price: 91.50, qty: 1000 }, { price: 90.96, qty: 1000 }],
      totalPnL: 5400.00, riskReward: 5.40, returnOnPosition: 0.0202, positionValue: 267000,
      entryReason: "Oil asset based on turning point lines", exitReason: null,
      conclusions: null, chartUrl: "https://www.tradingview.com/x/bFYgCj18/", dailyHigh: 93.60, dailyClose: 93.56 },
    { date: "2026-03-06", month: 3, symbol: "PNC", direction: "LONG", tradeType: "Retest Long", isSwingContinuation: false,
      buyLegs: [{ price: 207.15, qty: 50 }], sellLegs: [],
      totalPnL: null, riskReward: null, returnOnPosition: null, positionValue: 10358,
      entryReason: "", exitReason: null, conclusions: null, chartUrl: null, dailyHigh: 209.00, dailyClose: 206.12 },
    { date: "2026-03-06", month: 3, symbol: "KKR", direction: "LONG", tradeType: "Retest Long", isSwingContinuation: false,
      buyLegs: [{ price: 91.99, qty: 45.9136 }], sellLegs: [],
      totalPnL: null, riskReward: null, returnOnPosition: null, positionValue: 4224,
      entryReason: "", exitReason: null, conclusions: null, chartUrl: null, dailyHigh: 93.06, dailyClose: 91.33 },
    { date: "2026-03-06", month: 3, symbol: "C", direction: "LONG", tradeType: "Retest Long", isSwingContinuation: false,
      buyLegs: [{ price: 104.62, qty: 11 }], sellLegs: [{ price: 115.54, qty: 11 }],
      totalPnL: 115.16, riskReward: 0.12, returnOnPosition: 0.1001, positionValue: 1151,
      entryReason: "", exitReason: null, conclusions: null, chartUrl: null, dailyHigh: 106.59, dailyClose: 106.53 },
    { date: "2026-03-06", month: 3, symbol: "PATK", direction: "LONG", tradeType: "Retest Long", isSwingContinuation: false,
      buyLegs: [{ price: 115.98, qty: 65 }], sellLegs: [],
      totalPnL: null, riskReward: null, returnOnPosition: null, positionValue: 7539,
      entryReason: "Support line, Fib 0.382", exitReason: null,
      conclusions: null, chartUrl: "https://www.tradingview.com/x/dTi9Dv4N/", dailyHigh: 118.67, dailyClose: 115.81 },
    { date: "2026-03-06", month: 3, symbol: "ALNY", direction: "LONG", tradeType: "Retest Long", isSwingContinuation: false,
      buyLegs: [{ price: 313.15, qty: 6 }], sellLegs: [],
      totalPnL: null, riskReward: null, returnOnPosition: null, positionValue: 1879,
      entryReason: "CCI/RSI at lower line, D9 green, Fib 0.618, support line", exitReason: null,
      conclusions: null, chartUrl: "https://www.tradingview.com/x/BfExHaj5/", dailyHigh: 321.17, dailyClose: 320.66 },
    { date: "2026-03-06", month: 3, symbol: "EUR-USD", direction: "LONG", tradeType: "Earnings", isSwingContinuation: false,
      buyLegs: [{ price: 1.16, qty: 2 }], sellLegs: [{ price: 1.16, qty: 2 }],
      totalPnL: 90.00, riskReward: 0.09, returnOnPosition: 0.0004, positionValue: 232190,
      entryReason: "", exitReason: null, conclusions: null, chartUrl: null, dailyHigh: null, dailyClose: null },
    { date: "2026-03-09", month: 3, symbol: "BLKB", direction: "LONG", tradeType: "Retest Long", isSwingContinuation: false,
      buyLegs: [{ price: 47.24, qty: 50 }], sellLegs: [{ price: 39.97, qty: 50 }],
      totalPnL: -368.66, riskReward: -0.37, returnOnPosition: -0.1561, positionValue: 2362,
      entryReason: "Support line, D9 green, Bollinger support, CCI lower line", exitReason: null,
      conclusions: null, chartUrl: "https://www.tradingview.com/x/gcmeRt94/", dailyHigh: 47.96, dailyClose: 47.16 },
    { date: "2026-03-09", month: 3, symbol: "Oil", direction: "LONG", tradeType: "Breakout", isSwingContinuation: false,
      buyLegs: [{ price: 93.23, qty: 10 }, { price: 92.58, qty: 10 }, { price: 93.00, qty: 10 }],
      sellLegs: [{ price: 93.25, qty: 10 }, { price: 94.58, qty: 10 }, { price: 91.67, qty: 10 }],
      totalPnL: 690.00, riskReward: 0.69, returnOnPosition: 0.0025, positionValue: 278810,
      entryReason: "Reports and breakout", exitReason: "TP", conclusions: null, chartUrl: null, dailyHigh: null, dailyClose: null },
    { date: "2026-03-11", month: 3, symbol: "Gold", direction: "SHORT", tradeType: "Earnings", isSwingContinuation: false,
      buyLegs: [{ price: 5113.45, qty: 20 }], sellLegs: [{ price: 5188.00, qty: 20 }],
      totalPnL: 1491.00, riskReward: 1.49, returnOnPosition: 0.0144, positionValue: 103760,
      entryReason: "", exitReason: null, conclusions: null, chartUrl: null, dailyHigh: null, dailyClose: null },
    { date: "2026-03-11", month: 3, symbol: "Oil", direction: "LONG", tradeType: "Earnings", isSwingContinuation: false,
      buyLegs: [{ price: 85.65, qty: 2 }], sellLegs: [{ price: 92.85, qty: 1 }, { price: 89.92, qty: 1 }],
      totalPnL: 1147.00, riskReward: 1.15, returnOnPosition: 0.0670, positionValue: 17130,
      entryReason: "", exitReason: null, conclusions: null, chartUrl: null, dailyHigh: null, dailyClose: null },
    { date: "2026-03-11", month: 3, symbol: "Bitcoin FTMO", direction: "SHORT", tradeType: "Earnings", isSwingContinuation: false,
      buyLegs: [{ price: 71511.50, qty: 1 }, { price: 72136.00, qty: 1 }],
      sellLegs: [{ price: 70425.00, qty: 1 }, { price: 70115.00, qty: 1 }],
      totalPnL: -3107.50, riskReward: -3.11, returnOnPosition: -0.0221, positionValue: 140540,
      entryReason: "", exitReason: null, conclusions: null, chartUrl: null, dailyHigh: null, dailyClose: null },
    { date: "2026-03-11", month: 3, symbol: "EUR-USD", direction: "SHORT", tradeType: "Earnings", isSwingContinuation: false,
      buyLegs: [{ price: 1.15, qty: 2 }], sellLegs: [{ price: 1.16, qty: 2 }],
      totalPnL: 665.00, riskReward: 0.67, returnOnPosition: 0.0029, positionValue: 231110,
      entryReason: "", exitReason: null, conclusions: null, chartUrl: null, dailyHigh: null, dailyClose: null },
    { date: "2026-03-12", month: 3, symbol: "S&P", direction: "SHORT", tradeType: "Earnings", isSwingContinuation: false,
      buyLegs: [{ price: 6689.50, qty: 4 }, { price: 6692.50, qty: 3 }],
      sellLegs: [{ price: 6725.45, qty: 7 }],
      totalPnL: 2426.50, riskReward: 2.43, returnOnPosition: 0.0052, positionValue: 470782,
      entryReason: "", exitReason: null, conclusions: null, chartUrl: null, dailyHigh: null, dailyClose: null },
    { date: "2026-03-12", month: 3, symbol: "Oil", direction: "LONG", tradeType: "Earnings", isSwingContinuation: false,
      buyLegs: [{ price: 91.60, qty: 2 }], sellLegs: [{ price: 96.75, qty: 2 }],
      totalPnL: 1029.00, riskReward: 1.03, returnOnPosition: 0.0562, positionValue: 18320,
      entryReason: "", exitReason: null, conclusions: null, chartUrl: null, dailyHigh: null, dailyClose: null },
    { date: "2026-03-12", month: 3, symbol: "WING", direction: "LONG", tradeType: "Retest Long", isSwingContinuation: false,
      buyLegs: [{ price: 204.64, qty: 20 }], sellLegs: [{ price: 156.81, qty: 20 }],
      totalPnL: -961.52, riskReward: -0.96, returnOnPosition: -0.2349, positionValue: 4093,
      entryReason: "", exitReason: null, conclusions: null, chartUrl: null, dailyHigh: 210.55, dailyClose: 193.11 },
    { date: "2026-03-12", month: 3, symbol: "CAE", direction: "LONG", tradeType: "Retest Long", isSwingContinuation: false,
      buyLegs: [{ price: 27.75, qty: 322.5806 }], sellLegs: [],
      totalPnL: null, riskReward: null, returnOnPosition: null, positionValue: 8952,
      entryReason: "", exitReason: null, conclusions: null, chartUrl: null, dailyHigh: 28.39, dailyClose: 27.07 },
    { date: "2026-03-12", month: 3, symbol: "OMF", direction: "LONG", tradeType: "Retest Long", isSwingContinuation: false,
      buyLegs: [{ price: 52.63, qty: 150 }], sellLegs: [{ price: 45.97, qty: 150 }],
      totalPnL: -1003.40, riskReward: -1.00, returnOnPosition: -0.1271, positionValue: 7894,
      entryReason: "", exitReason: null, conclusions: null, chartUrl: null, dailyHigh: 53.03, dailyClose: 52.69 },
    { date: "2026-03-13", month: 3, symbol: "Bitcoin FTMO", direction: "LONG", tradeType: "Retest Long", isSwingContinuation: false,
      buyLegs: [{ price: 72775.00, qty: 4 }], sellLegs: [{ price: 72797.50, qty: 4 }],
      totalPnL: 90.00, riskReward: 0.09, returnOnPosition: 0.0003, positionValue: 291100,
      entryReason: "", exitReason: null, conclusions: null, chartUrl: null, dailyHigh: null, dailyClose: null },
    { date: "2026-03-15", month: 3, symbol: "EUR-USD", direction: "LONG", tradeType: "Earnings", isSwingContinuation: false,
      buyLegs: [{ price: 1.15, qty: 4.5 }], sellLegs: [{ price: 1.15, qty: 2.25 }, { price: 1.15, qty: 2.25 }],
      totalPnL: 1904.85, riskReward: 1.90, returnOnPosition: 0.0037, positionValue: 517289,
      entryReason: "", exitReason: null, conclusions: null, chartUrl: null, dailyHigh: null, dailyClose: null },
    { date: "2026-03-16", month: 3, symbol: "S&P", direction: "LONG", tradeType: "Earnings", isSwingContinuation: false,
      buyLegs: [{ price: 6720.00, qty: 1.5 }], sellLegs: [{ price: 6735.00, qty: 1.5 }],
      totalPnL: 225.00, riskReward: 0.23, returnOnPosition: 0.0022, positionValue: 100800,
      entryReason: "", exitReason: null, conclusions: null, chartUrl: null, dailyHigh: null, dailyClose: null },
    { date: "2026-03-16", month: 3, symbol: "SOUN", direction: "LONG", tradeType: "Retest Long", isSwingContinuation: false,
      buyLegs: [{ price: 7.26, qty: 30.12 }], sellLegs: [],
      totalPnL: null, riskReward: null, returnOnPosition: null, positionValue: 219,
      entryReason: "Support point, D9 green, RSI -30, Bollinger support", exitReason: null,
      conclusions: null, chartUrl: "https://www.tradingview.com/x/aS7gqw7B/", dailyHigh: null, dailyClose: null },
    { date: "2026-03-17", month: 3, symbol: "S&P", direction: "SHORT", tradeType: "Earnings", isSwingContinuation: false,
      buyLegs: [{ price: 6735.00, qty: 2 }], sellLegs: [{ price: 6771.50, qty: 2 }],
      totalPnL: 730.00, riskReward: 0.73, returnOnPosition: 0.0054, positionValue: 135430,
      entryReason: "", exitReason: null, conclusions: null, chartUrl: null, dailyHigh: null, dailyClose: null },
    { date: "2026-03-18", month: 3, symbol: "S&P", direction: "LONG", tradeType: "Earnings", isSwingContinuation: false,
      buyLegs: [{ price: 6730.00, qty: 2 }, { price: 6691.12, qty: 1 }],
      sellLegs: [{ price: 6706.25, qty: 2 }, { price: 6652.25, qty: 1 }],
      totalPnL: -863.70, riskReward: -0.86, returnOnPosition: -0.0043, positionValue: 201511,
      entryReason: "", exitReason: null, conclusions: null, chartUrl: null, dailyHigh: null, dailyClose: null },
    { date: "2026-03-18", month: 3, symbol: "Bitcoin FTMO", direction: "SHORT", tradeType: "Earnings", isSwingContinuation: false,
      buyLegs: [{ price: 71252.00, qty: 1 }], sellLegs: [{ price: 71320.00, qty: 1 }],
      totalPnL: 68.00, riskReward: 0.07, returnOnPosition: 0.0010, positionValue: 71320,
      entryReason: "", exitReason: null, conclusions: null, chartUrl: null, dailyHigh: null, dailyClose: null },
    { date: "2026-03-18", month: 3, symbol: "EUR-USD", direction: "LONG", tradeType: "Earnings", isSwingContinuation: false,
      buyLegs: [{ price: 1.16, qty: 8 }], sellLegs: [{ price: 1.16, qty: 8 }],
      totalPnL: -1120.00, riskReward: -1.12, returnOnPosition: -0.0012, positionValue: 925920,
      entryReason: "", exitReason: null, conclusions: null, chartUrl: null, dailyHigh: null, dailyClose: null },
    { date: "2026-03-18", month: 3, symbol: "S&P", direction: "SHORT", tradeType: "Earnings", isSwingContinuation: false,
      buyLegs: [{ price: 6690.00, qty: 3 }], sellLegs: [{ price: 6706.13, qty: 3 }],
      totalPnL: 483.90, riskReward: 0.48, returnOnPosition: 0.0024, positionValue: 201184,
      entryReason: "", exitReason: null, conclusions: null, chartUrl: null, dailyHigh: null, dailyClose: null },
    { date: "2026-03-18", month: 3, symbol: "Gold", direction: "LONG", tradeType: "Earnings", isSwingContinuation: false,
      buyLegs: [{ price: 4856.99, qty: 20 }], sellLegs: [{ price: 4803.80, qty: 20 }],
      totalPnL: -1063.80, riskReward: -1.06, returnOnPosition: -0.0110, positionValue: 97140,
      entryReason: "", exitReason: null, conclusions: null, chartUrl: null, dailyHigh: null, dailyClose: null },
    { date: "2026-03-18", month: 3, symbol: "EUR-USD", direction: "LONG", tradeType: "Earnings", isSwingContinuation: false,
      buyLegs: [{ price: 1.15, qty: 2.5 }, { price: 1.16, qty: 2 }],
      sellLegs: [{ price: 1.15, qty: 2.5 }, { price: 1.16, qty: 2 }],
      totalPnL: -1712.50, riskReward: -1.71, returnOnPosition: -0.0033, positionValue: 520805,
      entryReason: "", exitReason: null, conclusions: null, chartUrl: null, dailyHigh: null, dailyClose: null },
    { date: "2026-03-19", month: 3, symbol: "AZZ", direction: "LONG", tradeType: "Retest Long", isSwingContinuation: false,
      buyLegs: [{ price: 119.78, qty: 100.4016 }], sellLegs: [],
      totalPnL: null, riskReward: null, returnOnPosition: null, positionValue: 12026,
      entryReason: "Fib 0.382, support line, D9 green daily", exitReason: null,
      conclusions: null, chartUrl: "https://www.tradingview.com/x/Nt0wC2JM/", dailyHigh: 122.30, dailyClose: 121.26 },
    { date: "2026-03-20", month: 3, symbol: "APPL", direction: "LONG", tradeType: "Retest Long", isSwingContinuation: false,
      buyLegs: [{ price: 247.18, qty: 35 }], sellLegs: [],
      totalPnL: null, riskReward: null, returnOnPosition: null, positionValue: 8651,
      entryReason: "", exitReason: null, conclusions: null, chartUrl: null, dailyHigh: null, dailyClose: null },
    { date: "2026-03-20", month: 3, symbol: "FMV", direction: "LONG", tradeType: "Retest Long", isSwingContinuation: false,
      buyLegs: [{ price: 223.66, qty: 77 }], sellLegs: [{ price: 252.78, qty: 40 }],
      totalPnL: 1159.86, riskReward: 1.16, returnOnPosition: 0.0673, positionValue: 17222,
      entryReason: "", exitReason: null, conclusions: null, chartUrl: null, dailyHigh: null, dailyClose: null },
    { date: "2026-03-19", month: 3, symbol: "CANA", direction: "LONG", tradeType: "Retest Long", isSwingContinuation: false,
      buyLegs: [{ price: 285.23, qty: 1.9 }], sellLegs: [],
      totalPnL: null, riskReward: null, returnOnPosition: null, positionValue: 542,
      entryReason: "Retest point, D9 green, shrinking red volumes", exitReason: null,
      conclusions: null, chartUrl: "https://www.tradingview.com/x/3bKMfXw4/", dailyHigh: null, dailyClose: null },
    { date: "2026-03-19", month: 3, symbol: "CCJ", direction: "LONG", tradeType: "Retest Long", isSwingContinuation: false,
      buyLegs: [{ price: 104.06, qty: 9.71 }], sellLegs: [],
      totalPnL: null, riskReward: null, returnOnPosition: null, positionValue: 1010,
      entryReason: "Support point, D9 green, RSI2 low", exitReason: null,
      conclusions: null, chartUrl: "https://www.tradingview.com/x/gtu25676/", dailyHigh: 107.40, dailyClose: 106.60 },
    { date: "2026-03-24", month: 3, symbol: "EUR-USD", direction: "LONG", tradeType: "Earnings", isSwingContinuation: false,
      buyLegs: [{ price: 1.16, qty: 4 }], sellLegs: [{ price: 1.16, qty: 4 }],
      totalPnL: -972.00, riskReward: -0.97, returnOnPosition: -0.0021, positionValue: 465092,
      entryReason: "", exitReason: null, conclusions: null, chartUrl: null, dailyHigh: null, dailyClose: null },
    { date: "2026-03-24", month: 3, symbol: "Oil", direction: "SHORT", tradeType: "Earnings", isSwingContinuation: false,
      buyLegs: [{ price: 92.94, qty: 5 }], sellLegs: [{ price: 93.00, qty: 5 }],
      totalPnL: 30.00, riskReward: 0.03, returnOnPosition: 0.0006, positionValue: 46500,
      entryReason: "", exitReason: null, conclusions: null, chartUrl: null, dailyHigh: null, dailyClose: null },
    { date: "2026-03-20", month: 3, symbol: "UBS", direction: "LONG", tradeType: "Retest Long", isSwingContinuation: false,
      buyLegs: [{ price: 36.56, qty: 28.73 }], sellLegs: [],
      totalPnL: null, riskReward: null, returnOnPosition: null, positionValue: 1050,
      entryReason: "Retest point", exitReason: null,
      conclusions: null, chartUrl: "https://www.tradingview.com/x/Hhx0ZFlT/", dailyHigh: 37.40, dailyClose: 36.73 },
    { date: "2026-03-25", month: 3, symbol: "OKLO", direction: "LONG", tradeType: "Retest Long", isSwingContinuation: false,
      buyLegs: [{ price: 56.18, qty: 55 }], sellLegs: [],
      totalPnL: null, riskReward: null, returnOnPosition: null, positionValue: 3090,
      entryReason: "", exitReason: null, conclusions: null, chartUrl: null, dailyHigh: 57.65, dailyClose: 55.27 },
    { date: "2026-03-25", month: 3, symbol: "URBN", direction: "LONG", tradeType: "Retest Long", isSwingContinuation: false,
      buyLegs: [{ price: 61.23, qty: 150.1501 }], sellLegs: [{ price: 61.86, qty: 150.1501 }],
      totalPnL: 90.24, riskReward: 0.09, returnOnPosition: 0.0098, positionValue: 9194,
      entryReason: "", exitReason: null, conclusions: null, chartUrl: null, dailyHigh: 63.25, dailyClose: 61.47 },
    { date: "2026-03-26", month: 3, symbol: "Oil", direction: "SHORT", tradeType: "Earnings", isSwingContinuation: false,
      buyLegs: [{ price: 91.99, qty: 5 }], sellLegs: [{ price: 94.50, qty: 5 }],
      totalPnL: 1255.00, riskReward: 1.26, returnOnPosition: 0.0266, positionValue: 47250,
      entryReason: "", exitReason: null, conclusions: null, chartUrl: null, dailyHigh: null, dailyClose: null },
    { date: "2026-03-26", month: 3, symbol: "Oil", direction: "LONG", tradeType: "Earnings", isSwingContinuation: false,
      buyLegs: [{ price: 93.00, qty: 5 }], sellLegs: [{ price: 99.50, qty: 5 }],
      totalPnL: 3250.00, riskReward: 3.25, returnOnPosition: 0.0699, positionValue: 46500,
      entryReason: "", exitReason: null, conclusions: null, chartUrl: null, dailyHigh: null, dailyClose: null },
    { date: "2026-03-27", month: 3, symbol: "Bitcoin FTMO", direction: "LONG", tradeType: "Earnings", isSwingContinuation: false,
      buyLegs: [{ price: 66396.00, qty: 1 }, { price: 66395.00, qty: 1 }],
      sellLegs: [{ price: 66223.00, qty: 1 }, { price: 65697.50, qty: 1 }],
      totalPnL: -870.50, riskReward: -0.87, returnOnPosition: -0.0066, positionValue: 132791,
      entryReason: "", exitReason: null, conclusions: null, chartUrl: null, dailyHigh: null, dailyClose: null },
    { date: "2026-03-27", month: 3, symbol: "UBS", direction: "LONG", tradeType: "Retest Long", isSwingContinuation: false,
      buyLegs: [{ price: 36.57, qty: 283.28 }], sellLegs: [],
      totalPnL: null, riskReward: null, returnOnPosition: null, positionValue: 10360,
      entryReason: "D9 green, CCI/RSI lower line, Fib 0.618", exitReason: null,
      conclusions: null, chartUrl: "https://www.tradingview.com/x/K4CfLxQf/", dailyHigh: 37.08, dailyClose: 36.41 },
    { date: "2026-03-27", month: 3, symbol: "NTRA", direction: "LONG", tradeType: "Retest Long", isSwingContinuation: false,
      buyLegs: [{ price: 183.54, qty: 36.8867 }], sellLegs: [],
      totalPnL: null, riskReward: null, returnOnPosition: null, positionValue: 6770,
      entryReason: "", exitReason: null,
      conclusions: null, chartUrl: "https://www.tradingview.com/x/I0paGxV8/", dailyHigh: 195.99, dailyClose: 182.65 },
    { date: "2026-03-30", month: 3, symbol: "Bitcoin FTMO", direction: "SHORT", tradeType: "Earnings", isSwingContinuation: false,
      buyLegs: [{ price: 67233.33, qty: 1 }], sellLegs: [{ price: 66823.00, qty: 1 }],
      totalPnL: -410.33, riskReward: -0.41, returnOnPosition: -0.0061, positionValue: 66823,
      entryReason: "", exitReason: null, conclusions: null, chartUrl: null, dailyHigh: null, dailyClose: null },
    { date: "2026-03-30", month: 3, symbol: "Oil FTMO", direction: "LONG", tradeType: "Earnings", isSwingContinuation: false,
      buyLegs: [{ price: 104.62, qty: 10 }], sellLegs: [{ price: 104.80, qty: 10 }],
      totalPnL: 176.00, riskReward: 0.18, returnOnPosition: 0.0017, positionValue: 104623,
      entryReason: "", exitReason: null, conclusions: null, chartUrl: null, dailyHigh: null, dailyClose: null },
    { date: "2026-03-30", month: 3, symbol: "Gold", direction: "LONG", tradeType: "Earnings", isSwingContinuation: false,
      buyLegs: [{ price: 4568.00, qty: 10 }], sellLegs: [{ price: 4606.00, qty: 10 }],
      totalPnL: 380.00, riskReward: 0.38, returnOnPosition: 0.0083, positionValue: 45680,
      entryReason: "", exitReason: null, conclusions: null, chartUrl: null, dailyHigh: null, dailyClose: null },
  ];

  console.log(`Creating ${trades.length} trades...`);

  for (const t of trades) {
    const allLegs = [
      ...t.buyLegs.map((l, i) => ({
        legType: "BUY" as const,
        price: l.price,
        quantity: l.qty,
        commission: comm(l.price, l.qty),
        legOrder: i + 1,
      })),
      ...t.sellLegs.map((l, i) => ({
        legType: "SELL" as const,
        price: l.price,
        quantity: l.qty,
        commission: comm(l.price, l.qty),
        legOrder: i + 1,
      })),
    ];

    const totalBuyQty = t.buyLegs.reduce((s, l) => s + l.qty, 0);
    const totalSellQty = t.sellLegs.reduce((s, l) => s + l.qty, 0);
    const totalShares = Math.max(totalBuyQty, totalSellQty);
    const sharesInProcess = Math.abs(totalBuyQty - totalSellQty);
    const isCompleted = t.sellLegs.length > 0 && sharesInProcess < 0.1;

    const avgBuy = totalBuyQty > 0
      ? t.buyLegs.reduce((s, l) => s + l.price * l.qty, 0) / totalBuyQty
      : 0;
    const avgSell = totalSellQty > 0
      ? t.sellLegs.reduce((s, l) => s + l.price * l.qty, 0) / totalSellQty
      : 0;
    const totalComm = allLegs.reduce((s, l) => s + l.commission, 0);

    await prisma.trade.create({
      data: {
        accountId: account.id,
        tradeDate: new Date(t.date),
        month: t.month,
        symbol: t.symbol,
        direction: t.direction,
        tradeType: t.tradeType,
        isSwingContinuation: t.isSwingContinuation,
        totalPositionValue: t.positionValue,
        totalShares,
        sharesInProcess,
        avgBuyPrice: avgBuy,
        avgSellPrice: avgSell > 0 ? avgSell : null,
        totalPnL: t.totalPnL,
        riskReward: t.riskReward,
        returnOnPosition: t.returnOnPosition,
        riskAmount: t.month === 2 ? 1000 : null,
        totalCommissions: totalComm,
        isCompleted,
        entryReason: t.entryReason,
        exitReason: t.exitReason,
        conclusions: t.conclusions,
        chartUrl: t.chartUrl,
        dailyHigh: t.dailyHigh,
        dailyClose: t.dailyClose,
        entries: { create: allLegs },
      },
    });
  }

  console.log(`Done! Seeded ${trades.length} trades (Jan: 1, Feb: ${trades.length - 1}).`);
  console.log(`Account ID: ${account.id}`);

  await prisma.$disconnect();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
