// 1053 Laurel Ct NW · Unit 2 — property payment statement.
//
// Parsed verbatim from:
//   Property_Statement_Report_1053LaurelCtNW_ID721092-2.xlsx
//   Date range: Jan 1, 2026 – Dec 31, 2026 (rows cover Jan–Jun 2026)
//   Generated by Asaf Hamo on Jul 9, 2026 at 07:39 PM, America/New_York
//
// Landlord: Asaf Hamo · hamofamily5@gmail.com · (678) 576-4543
// Property & Units: 1053 Laurel Ct NW · Unit 2 (2-unit property)
// Address (per source): Laurel Ln NE, Rockdale County, GA, 30012, US
//
// Stored as a sibling property to Unit 1 so each unit keeps its own tenant and
// ledger. Every statement line is reproduced below in source order.

import type { PropertyStatement } from "../property-import";

export const LAUREL_CT_UNIT2_STATEMENT: PropertyStatement = {
  nickname: "1053 Laurel Ct NW, Unit 2",
  address: "1053 Laurel Ct NW, Unit 2, Rockdale County, GA, 30012, US",
  notes: [
    "2-unit property; this statement covers Unit 2.",
    "Landlord: Asaf Hamo · hamofamily5@gmail.com · (678) 576-4543.",
    "Imported from Property_Statement_Report_1053LaurelCtNW_ID721092-2.xlsx",
    "(statement range Jan 1 – Dec 31, 2026; generated Jul 9, 2026, America/New_York).",
  ].join(" "),
  tenants: [
    {
      name: "Gary Thomas",
      leaseStart: "2026-01-04", // first recorded rent
      leaseEnd: null, // ongoing
      monthlyRent: 1125,
      notes: "Tenant of record. Rent $1,125/mo.",
    },
  ],
  rows: [
    { date: "2026-01-04", rawCategory: "Rent", subCategory: "–", payee: "Gary Thomas", moneyIn: 1125.0, moneyOut: 0 },
    { date: "2026-01-09", rawCategory: "Management fees (Expense)", subCategory: "–", payee: "Gary Thomas", moneyIn: 0, moneyOut: 90.0 },
    { date: "2026-02-04", rawCategory: "Rent", subCategory: "–", payee: "Gary Thomas", moneyIn: 1125.0, moneyOut: 0 },
    { date: "2026-02-07", rawCategory: "Management fees (Expense)", subCategory: "–", payee: "Einat Hamo", moneyIn: 0, moneyOut: 90.0 },
    { date: "2026-03-04", rawCategory: "Rent", subCategory: "–", payee: "Gary Thomas", moneyIn: 1125.0, moneyOut: 0 },
    { date: "2026-03-10", rawCategory: "Management fees (Expense)", subCategory: "–", payee: "Gary Thomas", moneyIn: 0, moneyOut: 90.0 },
    { date: "2026-04-01", rawCategory: "Management fees (Expense)", subCategory: "–", payee: "Einat Hamo", moneyIn: 0, moneyOut: 90.0 },
    { date: "2026-04-04", rawCategory: "Rent", subCategory: "–", payee: "Gary Thomas", moneyIn: 1125.0, moneyOut: 0 },
    { date: "2026-05-01", rawCategory: "Management fees (Expense)", subCategory: "–", payee: "Einat Hamo", moneyIn: 0, moneyOut: 90.0 },
    { date: "2026-05-08", rawCategory: "Repairs", subCategory: "–", payee: "Gary Thomas", moneyIn: 0, moneyOut: 125.0 },
    { date: "2026-06-01", rawCategory: "Management fees (Expense)", subCategory: "–", payee: "Einat Hamo", moneyIn: 0, moneyOut: 90.0 },
    { date: "2026-06-04", rawCategory: "Rent", subCategory: "–", payee: "Gary Thomas", moneyIn: 1125.0, moneyOut: 0 },
  ],
};
