// 1053 Laurel Ct NW — property payment statement.
//
// Parsed verbatim from:
//   Property_Statement_Report_1053LaurelCtNW_ID721092.xlsx
//   Date range: Jan 1, 2026 – Dec 31, 2026 (rows cover Jan–Jun 2026)
//   Generated by Asaf Hamo on Jul 9, 2026 at 07:20 PM, America/New_York
//
// Landlord: Asaf Hamo · hamofamily5@gmail.com · (678) 576-4543
// Property & Units: 1053 Laurel Ct NW · Unit 1 (2-unit property)
// Address (per source): Laurel Ln NE, Rockdale County, GA, 30012, US
//
// Every "Date paid / Category / Sub-category / Payer-Payee / Money in / Money out"
// line from the spreadsheet is reproduced below in source order.

import type { PropertyStatement } from "../property-import";

export const LAUREL_CT_STATEMENT: PropertyStatement = {
  nickname: "1053 Laurel Ct NW",
  address: "1053 Laurel Ct NW, Unit 1, Rockdale County, GA, 30012, US",
  notes: [
    "2-unit property; this statement covers Unit 1.",
    "Landlord: Asaf Hamo · hamofamily5@gmail.com · (678) 576-4543.",
    "Imported from Property_Statement_Report_1053LaurelCtNW_ID721092.xlsx",
    "(statement range Jan 1 – Dec 31, 2026; generated Jul 9, 2026, America/New_York).",
  ].join(" "),
  tenants: [
    {
      name: "Sonya Scott",
      leaseStart: "2026-02-07", // first recorded rent; short-term / variable rent
      leaseEnd: null, // ongoing
      monthlyRent: null, // rent varies month to month (short-term rentals)
      notes: "Tenant of record. Rent varies by period ($1,750 / $1,200 / $1,150 / $650).",
    },
  ],
  rows: [
    { date: "2026-01-09", rawCategory: "Management fees (Expense)", subCategory: "–", payee: "Einat Hamo", moneyIn: 0, moneyOut: 72.0 },
    { date: "2026-02-07", rawCategory: "Rent", subCategory: "Short term rentals", payee: "Sonya Scott", moneyIn: 1750.0, moneyOut: 0 },
    { date: "2026-02-07", rawCategory: "Management fees (Expense)", subCategory: "–", payee: "Einat Hamo", moneyIn: 0, moneyOut: 140.0 },
    { date: "2026-03-10", rawCategory: "Management fees (Expense)", subCategory: "–", payee: "Sonya Scott", moneyIn: 0, moneyOut: 96.0 },
    { date: "2026-03-10", rawCategory: "Rent", subCategory: "–", payee: "Sonya Scott", moneyIn: 1200.0, moneyOut: 0 },
    { date: "2026-05-08", rawCategory: "Rent", subCategory: "–", payee: "Sonya Scott", moneyIn: 1150.0, moneyOut: 0 },
    { date: "2026-05-08", rawCategory: "Repairs", subCategory: "–", payee: "Sonya Scott", moneyIn: 0, moneyOut: 295.0 },
    { date: "2026-06-05", rawCategory: "Rent", subCategory: "–", payee: "Sonya Scott", moneyIn: 650.0, moneyOut: 0 },
    { date: "2026-06-05", rawCategory: "Management fees (Expense)", subCategory: "–", payee: "Einat Hamo", moneyIn: 0, moneyOut: 70.0 },
  ],
};
