// 1104 Windgate Cir NW — property payment statement.
//
// Parsed verbatim from:
//   Property_Statement_Report_1104WindgateCirNW_ID721085.xlsx
//   Date range: Jan 1, 2026 – Dec 31, 2026 (rows cover Jan–Jun 2026)
//   Generated by Asaf Hamo on Jul 9, 2026 at 07:48 PM, America/New_York
//
// Landlord: Asaf Hamo · hamofamily5@gmail.com · (678) 576-4543
// Property & Units: 1104 Windgate Cir NW (Single-family)
// Address (per source): 1104 Windgate Cir NW, Conyers, GA, 30012, US
//
// Every statement line is reproduced below in source order.

import type { PropertyStatement } from "../property-import";

export const WINDGATE_CIR_STATEMENT: PropertyStatement = {
  nickname: "1104 Windgate Cir NW",
  address: "1104 Windgate Cir NW, Conyers, GA, 30012, US",
  notes: [
    "Single-family rental.",
    "Landlord: Asaf Hamo · hamofamily5@gmail.com · (678) 576-4543.",
    "Imported from Property_Statement_Report_1104WindgateCirNW_ID721085.xlsx",
    "(statement range Jan 1 – Dec 31, 2026; generated Jul 9, 2026, America/New_York).",
  ].join(" "),
  tenants: [
    {
      name: "Jeremiah Chatman",
      leaseStart: "2026-01-09", // first recorded rent
      leaseEnd: null, // ongoing
      monthlyRent: 1400,
      notes: "Tenant of record. Rent $1,400/mo.",
    },
  ],
  rows: [
    { date: "2026-01-01", rawCategory: "Mortgage and Loans", subCategory: "–", payee: "Einat Hamo", moneyIn: 0, moneyOut: 982.29 },
    { date: "2026-01-09", rawCategory: "Rent", subCategory: "–", payee: "Jeremiah Chatman", moneyIn: 1400.0, moneyOut: 0 },
    { date: "2026-01-09", rawCategory: "Management fees (Expense)", subCategory: "–", payee: "Einat Hamo", moneyIn: 0, moneyOut: 112.0 },
    { date: "2026-02-01", rawCategory: "Mortgage and Loans", subCategory: "–", payee: "Einat Hamo", moneyIn: 0, moneyOut: 982.29 },
    { date: "2026-02-07", rawCategory: "Management fees (Expense)", subCategory: "–", payee: "Einat Hamo", moneyIn: 0, moneyOut: 112.0 },
    { date: "2026-02-09", rawCategory: "Rent", subCategory: "–", payee: "Jeremiah Chatman", moneyIn: 1400.0, moneyOut: 0 },
    { date: "2026-03-01", rawCategory: "Mortgage and Loans", subCategory: "–", payee: "Einat Hamo", moneyIn: 0, moneyOut: 982.29 },
    { date: "2026-03-09", rawCategory: "Rent", subCategory: "–", payee: "Jeremiah Chatman", moneyIn: 1400.0, moneyOut: 0 },
    { date: "2026-03-10", rawCategory: "Management fees (Expense)", subCategory: "–", payee: "Jeremiah Chatman", moneyIn: 0, moneyOut: 112.0 },
    { date: "2026-04-01", rawCategory: "Mortgage and Loans", subCategory: "–", payee: "Einat Hamo", moneyIn: 0, moneyOut: 982.29 },
    { date: "2026-04-04", rawCategory: "Management fees (Expense)", subCategory: "–", payee: "Einat Hamo", moneyIn: 0, moneyOut: 112.0 },
    { date: "2026-04-04", rawCategory: "Repairs", subCategory: "–", payee: "Einat Hamo", moneyIn: 0, moneyOut: 660.0 },
    { date: "2026-04-09", rawCategory: "Rent", subCategory: "–", payee: "Jeremiah Chatman", moneyIn: 1400.0, moneyOut: 0 },
    { date: "2026-05-01", rawCategory: "Mortgage and Loans", subCategory: "–", payee: "Einat Hamo", moneyIn: 0, moneyOut: 982.29 },
    { date: "2026-05-04", rawCategory: "Management fees (Expense)", subCategory: "–", payee: "Einat Hamo", moneyIn: 0, moneyOut: 112.0 },
    { date: "2026-05-09", rawCategory: "Rent", subCategory: "–", payee: "Jeremiah Chatman", moneyIn: 1400.0, moneyOut: 0 },
    { date: "2026-06-01", rawCategory: "Mortgage and Loans", subCategory: "–", payee: "Einat Hamo", moneyIn: 0, moneyOut: 982.29 },
    { date: "2026-06-04", rawCategory: "Management fees (Expense)", subCategory: "–", payee: "Einat Hamo", moneyIn: 0, moneyOut: 112.0 },
    { date: "2026-06-09", rawCategory: "Rent", subCategory: "–", payee: "Jeremiah Chatman", moneyIn: 1400.0, moneyOut: 0 },
  ],
};
