// 2505 Riverside Road — property payment statement.
//
// Parsed verbatim from:
//   Property_Statement_Report_2505RiversideRoad_ID720935.xlsx
//   Date range: Jan 1, 2026 – Dec 31, 2026 (rows cover Jan–Jun 2026)
//   Generated by Asaf Hamo on Jul 9, 2026 at 07:52 PM, America/New_York
//
// Landlord: Asaf Hamo · hamofamily5@gmail.com · (678) 576-4543
// Property & Units: 2505 Riverside Road (Single-family)
// Address (per source, verbatim): 2505 Riverside Road, Conyers, AL, 30013, US
//   NOTE: the source file records the state as "AL"; kept as-is for fidelity.
//
// Every statement line is reproduced below in source order. Some rental income
// is filed by the source under "Rent" and some under "Tenant charges & fees"
// (both preserved verbatim). The Jan income was received from "Chungdam USA CO.";
// subsequent months from tenant Youngmin choi.

import type { PropertyStatement } from "../property-import";

export const RIVERSIDE_ROAD_STATEMENT: PropertyStatement = {
  nickname: "2505 Riverside Road",
  address: "2505 Riverside Road, Conyers, AL, 30013, US",
  notes: [
    "Single-family rental.",
    "Landlord: Asaf Hamo · hamofamily5@gmail.com · (678) 576-4543.",
    "Source records state as 'AL' (kept verbatim).",
    "HOA/CAM billed by Heritage Property Management; mortgage labeled 'New mortgage for 2505'.",
    "Imported from Property_Statement_Report_2505RiversideRoad_ID720935.xlsx",
    "(statement range Jan 1 – Dec 31, 2026; generated Jul 9, 2026, America/New_York).",
  ].join(" "),
  tenants: [
    {
      name: "Youngmin choi",
      leaseStart: "2026-01-01",
      leaseEnd: null, // ongoing
      monthlyRent: 2450,
      notes: "Tenant of record. Rent $2,450/mo. Jan payment ($2,350) received from Chungdam USA CO.",
    },
  ],
  rows: [
    { date: "2026-01-01", rawCategory: "Dues and Fees", subCategory: "HOA/CAM/Strata", payee: "Heritage Property Management", moneyIn: 0, moneyOut: 200.0 },
    { date: "2026-01-01", rawCategory: "Mortgage and Loans", subCategory: "–", payee: "New mortgage for 2505", moneyIn: 0, moneyOut: 1891.39 },
    { date: "2026-01-01", rawCategory: "Tenant charges & fees", subCategory: "–", payee: "Chungdam USA CO.", moneyIn: 2350.0, moneyOut: 0 },
    { date: "2026-02-01", rawCategory: "Dues and Fees", subCategory: "HOA/CAM/Strata", payee: "Heritage Property Management", moneyIn: 0, moneyOut: 203.5 },
    { date: "2026-02-01", rawCategory: "Mortgage and Loans", subCategory: "–", payee: "New mortgage for 2505", moneyIn: 0, moneyOut: 1891.39 },
    { date: "2026-02-01", rawCategory: "Rent", subCategory: "–", payee: "Youngmin choi", moneyIn: 2450.0, moneyOut: 0 },
    { date: "2026-03-01", rawCategory: "Rent", subCategory: "–", payee: "Youngmin choi", moneyIn: 2450.0, moneyOut: 0 },
    { date: "2026-03-01", rawCategory: "Dues and Fees", subCategory: "HOA/CAM/Strata", payee: "Heritage Property Management", moneyIn: 0, moneyOut: 203.5 },
    { date: "2026-03-01", rawCategory: "Mortgage and Loans", subCategory: "–", payee: "New mortgage for 2505", moneyIn: 0, moneyOut: 1893.85 },
    { date: "2026-03-10", rawCategory: "Dues and Fees", subCategory: "HOA/CAM/Strata", payee: "Heritage Property Management", moneyIn: 0, moneyOut: 200.0 },
    { date: "2026-04-01", rawCategory: "Mortgage and Loans", subCategory: "–", payee: "New mortgage for 2505", moneyIn: 0, moneyOut: 1893.85 },
    { date: "2026-04-01", rawCategory: "Tenant charges & fees", subCategory: "–", payee: "Youngmin choi", moneyIn: 2450.0, moneyOut: 0 },
    { date: "2026-04-01", rawCategory: "Dues and Fees", subCategory: "HOA/CAM/Strata", payee: "Heritage Property Management", moneyIn: 0, moneyOut: 203.0 },
    { date: "2026-05-01", rawCategory: "Tenant charges & fees", subCategory: "–", payee: "Youngmin choi", moneyIn: 2450.0, moneyOut: 0 },
    { date: "2026-05-01", rawCategory: "Dues and Fees", subCategory: "HOA/CAM/Strata", payee: "Heritage Property Management", moneyIn: 0, moneyOut: 203.5 },
    { date: "2026-05-01", rawCategory: "Mortgage and Loans", subCategory: "–", payee: "New mortgage for 2505", moneyIn: 0, moneyOut: 1893.85 },
    { date: "2026-06-01", rawCategory: "Rent", subCategory: "–", payee: "Youngmin choi", moneyIn: 2450.0, moneyOut: 0 },
    { date: "2026-06-01", rawCategory: "Dues and Fees", subCategory: "HOA/CAM/Strata", payee: "Heritage Property Management", moneyIn: 0, moneyOut: 203.5 },
    { date: "2026-06-01", rawCategory: "Mortgage and Loans", subCategory: "–", payee: "New mortgage for 2505", moneyIn: 0, moneyOut: 1893.85 },
  ],
};
