// 260 North Peak Drive — property payment statement.
//
// Parsed verbatim from:
//   Property_Statement_Report_260NorthPeakDrive_ID720938.xlsx
//   Date range: Jan 1, 2026 – Dec 31, 2026 (rows cover Jan–Jun 2026)
//   Generated by Asaf Hamo on Jul 9, 2026 at 06:34 PM, America/New_York
//
// Landlord: Asaf Hamo · hamofamily5@gmail.com · (678) 576-4543
// Property & Units: 260 North Peak Drive (Single-family)
//
// Every "Date paid / Category / Sub-category / Payer-Payee / Money in / Money out"
// line from the spreadsheet is reproduced below in source order — EXCEPT the
// March 10th block of six identical mortgage payments, which is a portal export
// artifact (the source file duplicated one payment six times). March's real
// mortgage payment is the Mar 1 entry, matching every other month's cadence, so
// the six Mar 10 duplicates are omitted. One mortgage expense per month remains.

import type { PropertyStatement } from "../property-import";

export const NORTH_PEAK_STATEMENT: PropertyStatement = {
  nickname: "260 North Peak Drive",
  address: "260 N Peak Dr, Alpharetta, GA, 30022, US",
  notes: [
    "Single-family rental.",
    "Landlord: Asaf Hamo · hamofamily5@gmail.com · (678) 576-4543.",
    "Imported from Property_Statement_Report_260NorthPeakDrive_ID720938.xlsx",
    "(statement range Jan 1 – Dec 31, 2026; generated Jul 9, 2026, America/New_York).",
  ].join(" "),
  tenants: [
    {
      name: "Sarah Thorson",
      leaseStart: "2026-01-01", // inferred from the statement range; adjust if known
      leaseEnd: null, // ongoing
      monthlyRent: 5000,
      notes: "Tenant of record on the imported statement. Rent $5,000/mo.",
    },
  ],
  rows: [
    { date: "2026-01-01", rawCategory: "Mortgage and Loans", subCategory: "–", payee: "Einat Hamo", moneyIn: 0, moneyOut: 2735.06 },
    { date: "2026-01-06", rawCategory: "Tenant charges & fees", subCategory: "Trash service", payee: "Sarah Thorson", moneyIn: 60.77, moneyOut: 0 },
    { date: "2026-01-30", rawCategory: "Rent", subCategory: "–", payee: "Sarah Thorson", moneyIn: 5000, moneyOut: 0 },
    { date: "2026-01-31", rawCategory: "Tenant charges & fees", subCategory: "Electricity fee", payee: "Sarah Thorson", moneyIn: 159.27, moneyOut: 0 },
    { date: "2026-02-01", rawCategory: "Mortgage and Loans", subCategory: "–", payee: "Einat Hamo", moneyIn: 0, moneyOut: 2735.06 },
    { date: "2026-02-13", rawCategory: "Tenant charges & fees", subCategory: "Water fee", payee: "Sarah Thorson", moneyIn: 10.94, moneyOut: 0 },
    { date: "2026-02-13", rawCategory: "Tenant charges & fees", subCategory: "Water fee", payee: "Sarah Thorson", moneyIn: 140.48, moneyOut: 0 },
    { date: "2026-02-15", rawCategory: "Maintenance", subCategory: "Pest Control", payee: "Einat Hamo", moneyIn: 0, moneyOut: 237.5 },
    { date: "2026-02-27", rawCategory: "Rent", subCategory: "–", payee: "Sarah Thorson", moneyIn: 5000, moneyOut: 0 },
    { date: "2026-03-01", rawCategory: "Mortgage and Loans", subCategory: "–", payee: "Einat Hamo", moneyIn: 0, moneyOut: 2735.06 },
    { date: "2026-03-10", rawCategory: "Tenant charges & fees", subCategory: "Electricity fee", payee: "Sarah Thorson", moneyIn: 142.79, moneyOut: 0 },
    { date: "2026-03-11", rawCategory: "Tenant charges & fees", subCategory: "Electricity fee", payee: "Sarah Thorson", moneyIn: 178.71, moneyOut: 0 },
    { date: "2026-03-14", rawCategory: "Tenant charges & fees", subCategory: "Electricity fee", payee: "Sarah Thorson", moneyIn: 178.71, moneyOut: 0 },
    { date: "2026-03-31", rawCategory: "Rent", subCategory: "–", payee: "Sarah Thorson", moneyIn: 5000, moneyOut: 0 },
    { date: "2026-04-01", rawCategory: "Mortgage and Loans", subCategory: "–", payee: "Einat Hamo", moneyIn: 0, moneyOut: 2735.06 },
    { date: "2026-04-04", rawCategory: "Tenant charges & fees", subCategory: "Electricity fee", payee: "Sarah Thorson", moneyIn: 142.79, moneyOut: 0 },
    { date: "2026-04-04", rawCategory: "Tenant charges & fees", subCategory: "Trash service", payee: "Sarah Thorson", moneyIn: 60.92, moneyOut: 0 },
    { date: "2026-04-13", rawCategory: "Tenant charges & fees", subCategory: "Water fee", payee: "Sarah Thorson", moneyIn: 11.25, moneyOut: 0 },
    { date: "2026-04-13", rawCategory: "Tenant charges & fees", subCategory: "Water fee", payee: "Sarah Thorson", moneyIn: 114.43, moneyOut: 0 },
    { date: "2026-05-01", rawCategory: "Rent", subCategory: "–", payee: "Sarah Thorson", moneyIn: 5000, moneyOut: 0 },
    { date: "2026-05-01", rawCategory: "Mortgage and Loans", subCategory: "–", payee: "Einat Hamo", moneyIn: 0, moneyOut: 2735.06 },
    { date: "2026-05-08", rawCategory: "Tenant charges & fees", subCategory: "Electricity fee", payee: "Sarah Thorson", moneyIn: 156.98, moneyOut: 0 },
    { date: "2026-05-29", rawCategory: "Rent", subCategory: "–", payee: "Sarah Thorson", moneyIn: 5000, moneyOut: 0 },
    { date: "2026-06-01", rawCategory: "Mortgage and Loans", subCategory: "–", payee: "Einat Hamo", moneyIn: 0, moneyOut: 2735.06 },
    { date: "2026-06-29", rawCategory: "Rent", subCategory: "–", payee: "Sarah Thorson", moneyIn: 5000, moneyOut: 0 },
  ],
};
